baseURL = 'https://blog.kibb.dev/'
languageCode = 'en-us'
title = 'Kibb has a blog'
theme = "poison"

[params]
brand = "Kibb's deranged ranting."
dark_mode = true
description = "I have a blog now."
menu = [
    {Name = "About", URL = "/about/", HasChildren = false},
    {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},
]
github_url = "https://github.com/jkbbwr"

